databases:
 - name: budget
   databaseName: budget_be6i
   user: budget_be6i_user
   plan: free



services:
 - type: web
   name: budget
   env: ruby
   plan: free
   buildCommand: "./bin/render-build.sh"
   startCommand: bundle exec rails s
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: budget
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false
